services:
  backend:
    build: ./todo-backend
    ports:
      - "4000:4000"
    command: npm run dev

  frontend:
    build: ./todo-next-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev
