version: "3.8"

services:
  backend:
    build: ./todo-backend
    ports:
      - "4000:4000"
    container_name: todo-backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./todo-backend:/app
    command: npm run dev

  frontend:
    build: ./todo-next-app
    ports:
      - "3000:3000"
    container_name: todo-frontend
    restart: unless-stopped
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./todo-next-app:/app
    command: npm run dev
