import type { Metadata } from "next";
import "./globals.css";
import { inter } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';
import './globals.css'; // если используешь Tailwind

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <nav className="bg-gray-100 px-6 py-3 border-b flex gap-4">
          <Link href="/" className="hover:underline">Главная</Link>
          <Link href="/todos" className="hover:underline">Задачи</Link>
          <Link href="/about" className="hover:underline">О проекте</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}

